branches:
  except:
  - gh-pages

script:
  - echo "OK"

after_success:
  - ./gendoc.sh

env:
  global:
    secure: "Axte1dP7JA0if3Xb7ZwTAiQcfg3sTqJis5y9GDSdUirxBaWqhcaa/pbKKEVtRf4YbhDfeQcL6XGhnUtdGmjFaUlmMIUgifbg9s09U6HRAOjTgJ6bPWIlfpaI4KhUuGo31la1zAAtBmzeH9FeEYfC/zmDNm+zw4eV0ZS1bYLOPemZC9VWdm1FdR3oDvTVQhGT59ZmHyhg08r98NZe7ylJ8VjICF06tPZZGea56lO95swH3q2jwgoI6qm62a3r6NrSfUmtK3Ee30sn0RXVJGrcvt90dEi0yBEN013AWAp6LwyxbA8VYqXGowFfxB76CWHN5jzoddzdSsJozSzaorV1oICpEIcTlIAdf1dYnxNw1OulfZs9jqXj9frQOb8hLf3gcx8NZXR/oxzbmH8tXayzCWldu6NM6/Jz+1rgM8bwlq+L9KghF9SOs9cn4vUpxJaIZAZSQI6HmGll8zfHN9kBrgxMfaIreMjrZomQtZc7xqmP4voavsevaacCljho+8eMxrWwiwb2o+DXZychUTuBaI5paDOAzg51SSdNzYJDWjoo6i5Hx4t+Rm8pGn3puxnxerPTOmaiwxfDteXO8wGZbQVY2zo4yL5Lgm4VH38usPlVge2rj7H26+7AfQPWGXgYC08CD3ZPFY2UNvwp4kjx8Dpup+X10JXfBwvQ0Sq130Q="
