branches:
  except:
  - gh-pages

script:
  - echo "OK"

after_success:
  - ./gendoc.sh

env:
  global:
    secure: "d2+3KNfhK7FvdWyY1kf1PmQ7s/K9151zJA0ztyodOdJvks75/RXgdVai0TnRQx2MwKShtImaTTBYTKlNEkBgxmwQHCb/RHgIHbkncZbBsDo2c+FWk6fwd14tBdNndjaozleVPmURhrku5Idot2fziAtX+2SveNvXoDVkEWrZBH72GzFy4T8hflFY8mW5ZzOFzk7wc8AU5eaHRjINwzoSOmYbCd1XQ9wLFmbw+UQFp7oJJY/sKuKTCgxvvgPRjJ6L7dOXHgR/HjAfNavhlBq6TvLisXQK1Gh1d4NDE4H2F7RLBVfsV9X/ZHZzkZJF0RMFxCalj5j0nxeWNWXOvQdUFf0cB9ydOAePp1bwMVe0ikcXVZJAFJctxznNvQADCyg0WKR65NYIHTnA9muP11AuZS6FikmfBYPZjG83JAiRSMe6kbQyIOgrpF4fIBtperSncQ6fOC8tHPCaUbFTEjYiMI0CApP/nV5s5GbahYeq8Z9TQSpySLwjGF4wSvmkTq7MjeOg8SQ9qTsa26RgHAkCx8AZNkV/olPnbCqxkN4vVGTXDamo0T7CcN1hU24O9NXBddtWFQsdHbwt6Jb7DfosMG0PVyYf6IP4+ioGAlylXn3FXUcjLeKe/gmwsWzP9qcRmNLyzMDoVPpETWjGtVj7Z+AvT98wZ5AR5dfAt3qOcCo="
